### ISSUE TITLE
感谢开源项目 问题:创建项目中同步Schema的使用

### ISSUE THREAD

**Issue by shulu** [vran-dev/databasir#132]
首先感谢作者开源项目
上午刷HelloGitHub刚看到就部署下来玩玩了
我不太理解这个项目创建过程当中需要强制添加的同步Schema的作用 
然后找文档也没有对应的模块
烦请作者不吝赐教 这个具体的使用以及实际的作用
![image](https://user-images.githubusercontent.com/12324712/165727351-da7354fd-682b-4ca5-94bf-d68f204633bd.png)

**Comment by vran-dev** [comment]
@shulu 

因为不同的数据库对 database 和 schema 有不同的定义
- mysql：database 和 schema 其实都是数据库
- postgresql：database 里面存放了我们要同步的表结构，schema 一般默认是 public
- sqlserver：一般模式 database 是 master， schema 才是我们要同步的表结构

正是因为各个厂商的定义不同，才将 database 和 schema 都交给用户来填

**Comment by vran-dev** [comment]
当然这也是新项目前期综合权衡之下的决策，如果确实造成了很大的困惑，那么我会排期进行优化。

毕竟能让用户依靠直觉使用项目是我追求的用户体验之一

**Comment by shulu** [comment]
> @shulu
> 
> 因为不同的数据库对 database 和 schema 有不同的定义
> 
> * mysql：database 和 schema 其实都是数据库
> * postgresql：database 里面存放了我们要同步的表结构，schema 一般默认是 public
> * sqlserver：默认 database 是 master， 而 schema 里面才维护了我们要同步的表结构
> 
> 正是因为各个厂商的定义不同，才将 database 和 schema 都交给用户来填

我大概明白了一些 然后我去查阅了一下MYSQL资料 
如果没理解错的话 这个Schema是用来填写对应的数据库当中可以同步数据库的结构的库
因为我是用的是**MYSQL**所以这里应当填写**information_schema**

然后针对Reply 2:我想说 我出现这个问题主要还是因为我对mysql不够了解 并非是软件的原因

最后 感谢耐心回复 谢谢
