### ISSUE TITLE
Can add exporting excel

### ISSUE THREAD

**Issue by DataFormate** [vran-dev/databasir#145]
Could you please add the function of exporting to excel?
this tool is very practical，but it has fewer export options, especially lack of export to excel!
so ,could you please add the function of exporting to excel?

**Comment by vran-dev** [comment]
thx for your suggestion.
due to shortage of time, i would focus on core function recently (such as bugfix, more database type support).
but i also would try to support excel export, please keep following this project.

**Comment by DataFormate** [comment]
thank you for your reply. i can understand your situation. I have already downloaded the code locally and tried to write a function for exporting excel. Thank you so much for open-sourcing this useful tool

> thx for your suggestion. due to shortage of time, i would focus on core function recently (such as bugfix, more database type support). but i also would try to support excel export, please keep following this project.

**Comment by DataFormate** [comment]
thank you for your reply. i can understand your situation. I have already downloaded the code locally and tried to write a function for exporting excel. Thank you so much for open-sourcing this useful tool.




sunBURST
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vran-dev/databasir"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vran-dev/databasir] Can add exporting excel (Issue #145)





 
thx for your suggestion.
 due to shortage of time, i would focus on core function recently (such as bugfix, more database type support).
 but i also would try to support excel export, please keep following this project.
