### ISSUE TITLE
文档无法搜索列注释内容

### ISSUE THREAD

**Issue by all-aroundbadass** [vran-dev/databasir#180]
databasir 版本：最新 docker 版本
sql server 版本：2017
sql server 驱动版本：9.4.1.jre8
现在注释显示正常了，但是左侧的搜索栏里只能搜索表名，搜索注释和描述都不可以，如下图所示
![image](https://user-images.githubusercontent.com/26058690/168554064-91752cca-a4dd-4870-88ea-580b9718946a.png)

**Comment by vran-dev** [comment]
@all-aroundbadass 
左侧表列表是否展示了注释？ 目前我还没有复现这个情况，刷新页面试试

**Comment by all-aroundbadass** [comment]
> @all-aroundbadass 左侧表列表是否展示了注释？ 目前我还没有复现这个情况，刷新页面试试

展示了，注释的搜索指的表名还是列注释啊？如果是表名那没问题，如果是表内某字段注释那不行
![image](https://user-images.githubusercontent.com/26058690/168926310-66e56db3-3731-4bcb-bbf6-c7a8fb331e3d.png)

**Comment by vran-dev** [comment]
@all-aroundbadass  目前还不支持列的搜索
