### ISSUE TITLE
提示: 登录状态失效, 请重新登录

### ISSUE THREAD

**Issue by cys-home** [vran-dev/databasir#202]
databasir: latest  部署方式: docker
mysql: latest  部署方式: docker

内网部署

容器正常启动后, 进入登录页面, 输入默认的管理员名称和密码后, 成功进入主页面, 但会闪退到登录页面, 并提示: 登陆状态失效, 请重新登陆
多次重复登录均无法进入主页面

![问题](https://user-images.githubusercontent.com/54316827/169942036-0f4b2f29-757b-4979-b059-9af48402d93f.jpg)

**Comment by vran-dev** [comment]
@cys-home 

从日志来看，mysql 的时区是不是差了8 个小时？需要设置一下 mysql 的默认时区

**Comment by cys-home** [comment]
这是我的部署命令, 但还是有问题
# mysql
docker run -d --network databasir --name mysql_auto -e MYSQL_ROOT_PASSWORD=MySQLAutoService@ -e TZ=Asia/Shanghai mysql:latest
# databasir
docker run -d -p 8899:8080 --network databasir --name databasir_auto -e DATABASIR_DB_URL=mysql_auto:3306 -e DATABASIR_DB_USERNAME=root -e DATABASIR_DB_PASSWORD=MySQLAutoService@ -e TZ=Asia/Shanghai vrantt/databasir:latest

**Comment by cys-home** [comment]
找到问题了, 容器设置`TZ=Asia/Shanghai`时间后, 但因为我的本机时间比服务器时间慢30几分钟, 所以导致还是访问, 我将本机时间与服务器时间保持一致后, 问题解决
