### ISSUE TITLE
无法展示单个表信息

### ISSUE THREAD

**Issue by cys-home** [vran-dev/databasir#204]
我的数据库有100多张表, 创建项目并且点击同步后, 提示数据同步完成, 然后我点击左侧的单个表, 右侧并未展示表的详细信息

点击左侧的单个表后, F12可以看到已经获取到了响应的表数据, 并且还可以看到在持续发起list_manual_tasks的请求

**Comment by vran-dev** [comment]
目前部署的哪个版本？同步的数据库信息最好也提供一下

**Comment by cys-home** [comment]
> 目前部署的哪个版本？同步的数据库信息最好也提供一下

databasir: latest   部署方式: docker
mysql: latest 部署方式: docker

被同步的数据库版本: 5.7.27, 部署方式: docker
数据库信息: 字符集:utf8mb4, 排序规则:utf8mb4_unicode_ci

**Comment by vran-dev** [comment]
目前是场景可以重现吗？

可以观察一下后 databasir 的后台日志，是有输出 `ignore column` 等信息

**Comment by cys-home** [comment]
下面这张图, 是持续发起的请求
![持续发起请求](https://user-images.githubusercontent.com/54316827/170909435-34b6efd3-efaa-47c8-9fdc-61cc2cc94c3e.jpg)

下面这张图, 是点击某个表后, 获取的请求
![点击表后](https://user-images.githubusercontent.com/54316827/170909534-01505617-bba4-443d-901b-57068cecc7c5.jpg)

这是后台日志
![后台日志](https://user-images.githubusercontent.com/54316827/170909563-ce61a5ac-7e54-489a-8488-53eb6140f4ca.jpg)

**Comment by cys-home** [comment]
> ignore column

后台日志并没有ignore column等日志

**Comment by vran-dev** [comment]
从第一张截图的信息来看，返回的文档内容是有的，后端应该没问题。

那没有跳转就有可能是前端渲染出现了异常，可以查看浏览器的控制台是否有错误

**Comment by cys-home** [comment]
![IMG_20220530_110916](https://user-images.githubusercontent.com/54316827/170913140-c30f75f5-8000-4714-87d9-29d70afb2129.jpg)
![IMG_20220530_111115](https://user-images.githubusercontent.com/54316827/170913171-c2fefcf7-ea64-4e83-ac2f-463d4e71c4ec.jpg)
![IMG_20220530_111047](https://user-images.githubusercontent.com/54316827/170913193-473290dd-d07b-4e51-95b3-7b6425e01986.jpg)

**Comment by vran-dev** [comment]
![image](https://user-images.githubusercontent.com/12870335/170914646-687e687a-2770-4287-8c2d-fc97ea2f6499.png)

看看这里的控制台是否有错误日志

**Comment by cys-home** [comment]
是的, 点击单个表后, 会报错
![IMG_20220530_141210](https://user-images.githubusercontent.com/54316827/170928377-31848222-12db-4527-b87d-7196f4c9a40f.jpg)

**Comment by vran-dev** [comment]
chrome 浏览器版本低欲 69，升级即可
