### ISSUE TITLE
缺失表名注释

### ISSUE THREAD

**Issue by ljl0303** [vran-dev/databasir#230]

**Comment by vran-dev** [comment]
提供一下数据库版本信息，如果是 mysql 或者 oracle，可以参考文档进行配置：
 https://doc.databasir.com/faq/

**Comment by ljl0303** [comment]
useInformationSchema=true加上了即可~

**Comment by liws007** [comment]
![Snipaste_2022-07-20_10-39-17](https://user-images.githubusercontent.com/9987010/179884600-39a5d9a5-db32-400b-884d-52d2aea7f855.png)  添加了该配置，同步任务会卡死

**Comment by liws007** [comment]
![Snipaste_2022-07-20_10-44-15](https://user-images.githubusercontent.com/9987010/179884793-631cd991-b4ec-4304-999f-1d18c5c0aeb9.png)
添加了该配置，同步任务会卡死

**Comment by ljl0303** [comment]
> ![Snipaste_2022-07-20_10-44-15](https://user-images.githubusercontent.com/9987010/179884793-631cd991-b4ec-4304-999f-1d18c5c0aeb9.png) 添加了该配置，同步任务会卡死

抱歉才看到,我当时没注意这个问题,请问你是换了个连接参数解决吗
