### ISSUE TITLE
Security vulnerability responsible disclosure

### ISSUE THREAD

**Issue by ThomasTNO** [vran-dev/databasir#254]
I am trying to communicate a discovered vulnerability in Databasir through the email address associated with @vran-dev, without success.

Can you share a way to report these findings or create a security advisory?

Thanks in advance

**Comment by vran-dev** [comment]
@ThomasTNO  

thanks for your finding and sharing, maybe i was missing the email, it's so sorry.

back to the topic, first you may need to check if it is repeated as  [Databasir SSR](https://github.com/vran-dev/databasir/security/advisories/GHSA-r8m9-r74j-vc6m), if not i will create a security advisory.

**Comment by ThomasTNO** [comment]
Thanks for the quick response. It is different to [Databasir SSR](https://github.com/vran-dev/databasir/security/advisories/GHSA-r8m9-r74j-vc6m) and still persists in the latest release

**Comment by vran-dev** [comment]
> Thanks for the quick response. It is different to [Databasir SSR](https://github.com/vran-dev/databasir/security/advisories/GHSA-r8m9-r74j-vc6m) and still persists in the latest release

the advisory had been created,  and has invite you as collaborators, next step need your help to wirte details about this vulnerability. 

then i will review it and request CVE, thanks for your contribution

**Comment by vran-dev** [comment]
link here: https://github.com/vran-dev/databasir/security/advisories/GHSA-qvg8-427f-852q
