### ISSUE TITLE
Vulnerability: found a upload vuln

### ISSUE THREAD

**Issue by Alex111998** [vran-dev/databasir#272]
Risky path: /database_types/upload_driver
![image](https://user-images.githubusercontent.com/127834723/227765748-6946574d-9d75-4ae0-a57b-7d452b67af49.png)
![image](https://user-images.githubusercontent.com/127834723/227765981-6f700df2-333a-4b2e-ab8b-542a4590a05e.png)
Risk function: com.databasir.core.domain.database.service.DatabaseTypeService#uploadDriver

Because there is no security detection file suffix function, users can upload any file, or even upload it to other working directories
like upload a file to getshell

**Comment by vran-dev** [comment]
you are right, but the upload operation only available for admin.
