### ISSUE TITLE
表备注未能获取并显示

### ISSUE THREAD

**Issue by ccsen** [vran-dev/databasir#72]
有中文Comment的表同步后，文档信息里表的Comment列字段为空。
测试mysql版本 5.7.34。

**Comment by vran-dev** [comment]
@ccsen  

mysql 的 jdbc 驱动的限制，创建项目的时候连接需要添加属性 
```properties
useInformationSchema = true
```

**Comment by ccsen** [comment]
添加属性useInformationSchema = true 有效，问题解决。
