### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by Kerwin1202** [vran-dev/databasir#76]
1. 增加主流驱动，目前就两个 mysql, postgresql  如果怕增加更多导致容量，看能否以插件的形式展示
2. 我部署在 1h2g 百度云机器上 只有这个和 mysql 以及另一个docker 访问起来点击有点卡  以及点如图这个 会卡四五秒不跳转还以为不能点
![image](https://user-images.githubusercontent.com/16319833/162614185-c1954d4f-01c5-4cd9-9ce9-4adc41bae0eb.png)
3. UML 是否会保存呢，我测试刷新就没了。即反向操作表
![image](https://user-images.githubusercontent.com/16319833/162614330-34accd6e-2693-41e5-bfb9-6077493f80fc.png)

**Comment by vran-dev** [comment]
1. 指的是其他数据库的支持吗？ databasir 理论上支持任意有 JDBC 驱动的数据库，参考[文档](https://doc.databasir.com/#/README/database-extension/database-extension)
2. 这里会加一个交互动画
3. UML 目前还不支持保存 relation

thx
