### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by lovebetterworld** [vran-dev/databasir#86]
1：表的名称，建议也附加在表名后，可参考chiner的风格；
2：卡顿，操作不顺畅，多选操作后，会有明显卡顿；
3：感觉是好东西，但是需要完善的还有很多，加油，继续搞。

**Comment by vran-dev** [comment]
感谢你的建议

**Comment by vran-dev** [comment]
docker latest 版在表名后已显示 comment 信息
