### ISSUE TITLE
300多张表的库，同步很容易超时

### ISSUE THREAD

**Issue by jackey35** [vran-dev/databasir#93]
![image](https://user-images.githubusercontent.com/2055618/163513029-76c544cf-36aa-4d54-ae5a-64ca68d07c35.png)

**Comment by vran-dev** [comment]
感谢你的反馈
该问题实际为前端超时了，后端还在同步中，可以稍后查看。
不过在面对大数据量时同步的方式进行同步容易超时，为了更好的兼容各种场景，我会将其改为异步任务的形式。
欢迎通过首页二维码进群讨论

@jackey35

**Comment by vran-dev** [comment]
docker latest 版本已支持异步同步文档
